### ISSUE TITLE
GPU内存不够

### ISSUE THREAD

**Issue by Pamyuu** [bubbliiiing/ssd-pytorch#41]
RuntimeError: CUDA out of memory. Tried to allocate 1.62 GiB (GPU 0; 6.00 GiB total capacity; 921.75 MiB already allocated; 3.54 GiB free; 4.25 MiB cached)

需要1.62G，明明有空闲的3.54G，还是报错，Batchsize调到1还是报错，搜了好多博客也没解决，咋回事呀

**Comment by Pamyuu** [comment]
cuda=True，使用GPU计算，但是会报上面的错误
cuda=False，使用CPU进行计算，可以正常跑
这里应该不是GPU内存不够的问题，而且我把CUDA和CUDNN都卸载了，cuda=True情况下，还是会报上面的错误

**Comment by Pamyuu** [comment]
是不是CUDA版本和cudnn的版本对不上的原因呢？

**Comment by bubbliiiing** [comment]
ssd的话6G显存肯定够，应该是cuda和cudnn的问题

**Comment by Pamyuu** [comment]
问题解决了，不是CUDA，CUDNN的问题，在BIOS里调成独显模式就可以了，只用GPU0

**Comment by bubbliiiing** [comment]
这。。。

**Comment by bubbliiiing** [comment]
解决了就好

**Comment by Pamyuu** [comment]
实验室用联想拯救者的我们三个人都是这个问题，调成独显模式就可以了，不知道为啥...

**Comment by bubbliiiing** [comment]
只能说太玄学了
